// import { ApiService } from './api.service';
import { Injectable } from '@angular/core';
import { Api } from '../api';

@Injectable({
  providedIn: 'root',
})
export class ModelsService {
  // models: any = [
  //   {
  //     name: 'presensi',
  //     add: true,
  //     edit: true,
  //     delete: true,
  //     view: false,
  //     list: true,
  //     field: [
  //       {
  //         name: 'id',
  //         label: 'Id',
  //         primary: true,
  //         type: 'NO',
  //         validate: 'INTEGER',
  //         number: false,
  //         list: false,
  //         view: false,
  //         add: false,
  //         edit: false,
  //         sort: true,
  //         filtersearch: false,
  //         relation: false,
  //         relation_table: '',
  //         relation_field: '',
  //         relation_display: '',
  //         parent_filter: [],
  //         required: false,
  //         readonly: false,
  //         default: '',
  //         file: false,
  //       },
  //     ],
  //   },
  //   {
  //     name: 'karyawan',
  //     add: true,
  //     edit: true,
  //     delete: true,
  //     view: false,
  //     list: true,
  //     field: [
  //       {
  //         name: 'id',
  //         label: 'Id',
  //         primary: true,
  //         type: 'NO',
  //         validate: 'INTEGER',
  //         number: false,
  //         list: false,
  //         view: false,
  //         add: false,
  //         edit: false,
  //         sort: true,
  //         filtersearch: false,
  //         relation: false,
  //         relation_table: '',
  //         relation_field: '',
  //         relation_display: '',
  //         parent_filter: [],
  //         required: false,
  //         readonly: false,
  //         default: '',
  //         file: false,
  //       },
  //       {
  //         name: 'nama_karyawan',
  //         label: 'Nama Karyawan',
  //         primary: true,
  //         type: 'NO',
  //         validate: 'INTEGER',
  //         number: false,
  //         list: false,
  //         view: true,
  //         add: false,
  //         edit: false,
  //         sort: true,
  //         filtersearch: false,
  //         relation: false,
  //         relation_table: '',
  //         relation_field: '',
  //         relation_display: '',
  //         parent_filter: [],
  //         required: false,
  //         readonly: false,
  //         default: '',
  //         file: false,
  //       },
  //       {
  //         name: 'nik',
  //         label: 'NIK',
  //         primary: true,
  //         type: 'NO',
  //         validate: 'INTEGER',
  //         number: false,
  //         list: false,
  //         view: true,
  //         add: false,
  //         edit: false,
  //         sort: true,
  //         filtersearch: false,
  //         relation: false,
  //         relation_table: '',
  //         relation_field: '',
  //         relation_display: '',
  //         parent_filter: [],
  //         required: false,
  //         readonly: false,
  //         default: '',
  //         file: false,
  //       },
  //       {
  //         name: 'jabatan',
  //         label: 'Jabatan',
  //         primary: true,
  //         type: 'NO',
  //         validate: 'INTEGER',
  //         number: false,
  //         list: false,
  //         view: true,
  //         add: false,
  //         edit: false,
  //         sort: true,
  //         filtersearch: false,
  //         relation: false,
  //         relation_table: '',
  //         relation_field: '',
  //         relation_display: '',
  //         parent_filter: [],
  //         required: false,
  //         readonly: false,
  //         default: '',
  //         file: false,
  //       },
  //       {
  //         name: 'tanggal_lahir',
  //         label: 'Tanggal Lahir',
  //         primary: true,
  //         type: 'NO',
  //         validate: 'INTEGER',
  //         number: false,
  //         list: false,
  //         view: true,
  //         add: false,
  //         edit: false,
  //         sort: true,
  //         filtersearch: false,
  //         relation: false,
  //         relation_table: '',
  //         relation_field: '',
  //         relation_display: '',
  //         parent_filter: [],
  //         required: false,
  //         readonly: false,
  //         default: '',
  //         file: false,
  //       },
  //       {
  //         name: 'divisi_id',
  //         label: 'Divisi Id',
  //         primary: true,
  //         type: 'NO',
  //         validate: 'INTEGER',
  //         number: false,
  //         list: false,
  //         view: true,
  //         add: false,
  //         edit: false,
  //         sort: true,
  //         filtersearch: false,
  //         relation: true,
  //         relation_table: 'divisi',
  //         relation_field: 'id',
  //         relation_display: 'nama',
  //         parent_filter: [],
  //         required: false,
  //         readonly: false,
  //         default: '',
  //         file: false,
  //       },
  //       {
  //         name: 'lokasi_kerja',
  //         label: 'Lokasi Kerja',
  //         primary: true,
  //         type: 'NO',
  //         validate: 'INTEGER',
  //         number: false,
  //         list: false,
  //         view: true,
  //         add: false,
  //         edit: false,
  //         sort: true,
  //         filtersearch: false,
  //         relation: false,
  //         relation_table: '',
  //         relation_field: '',
  //         relation_display: '',
  //         parent_filter: [],
  //         required: false,
  //         readonly: false,
  //         default: '',
  //         file: false,
  //       },
  //       {
  //         name: 'telepon',
  //         label: 'Telepon',
  //         primary: true,
  //         type: 'NO',
  //         validate: 'INTEGER',
  //         number: false,
  //         list: false,
  //         view: true,
  //         add: false,
  //         edit: false,
  //         sort: true,
  //         filtersearch: false,
  //         relation: false,
  //         relation_table: '',
  //         relation_field: '',
  //         relation_display: '',
  //         parent_filter: [],
  //         required: false,
  //         readonly: false,
  //         default: '',
  //         file: false,
  //       },
  //       {
  //         name: 'alamat',
  //         label: 'Alamat',
  //         primary: true,
  //         type: 'NO',
  //         validate: 'INTEGER',
  //         number: false,
  //         list: false,
  //         view: true,
  //         add: false,
  //         edit: false,
  //         sort: true,
  //         filtersearch: false,
  //         relation: false,
  //         relation_table: '',
  //         relation_field: '',
  //         relation_display: '',
  //         parent_filter: [],
  //         required: false,
  //         readonly: false,
  //         default: '',
  //         file: false,
  //       },
  //       {
  //         name: 'deskripsi',
  //         label: 'Deskripsi',
  //         primary: true,
  //         type: 'NO',
  //         validate: 'INTEGER',
  //         number: false,
  //         list: false,
  //         view: true,
  //         add: false,
  //         edit: false,
  //         sort: true,
  //         filtersearch: false,
  //         relation: false,
  //         relation_table: '',
  //         relation_field: '',
  //         relation_display: '',
  //         parent_filter: [],
  //         required: false,
  //         readonly: false,
  //         default: '',
  //         file: false,
  //       },
  //       {
  //         name: 'img_photo_karyawan',
  //         label: 'Photo',
  //         primary: true,
  //         type: 'NO',
  //         validate: 'INTEGER',
  //         number: false,
  //         list: false,
  //         view: true,
  //         add: false,
  //         edit: false,
  //         sort: true,
  //         filtersearch: false,
  //         relation: false,
  //         relation_table: '',
  //         relation_field: '',
  //         relation_display: '',
  //         parent_filter: [],
  //         required: false,
  //         readonly: false,
  //         default: '',
  //         file: false,
  //       },
  //       {
  //         name: 'user_id',
  //         label: 'User',
  //         primary: true,
  //         type: 'NO',
  //         validate: 'INTEGER',
  //         number: false,
  //         list: false,
  //         view: false,
  //         add: false,
  //         edit: false,
  //         sort: true,
  //         filtersearch: false,
  //         relation: false,
  //         relation_table: '',
  //         relation_field: '',
  //         relation_display: '',
  //         parent_filter: [],
  //         required: false,
  //         readonly: false,
  //         default: '',
  //         file: false,
  //       },
  //       {
  //         name: 'active',
  //         label: 'Aktif',
  //         primary: true,
  //         type: 'NO',
  //         validate: 'INTEGER',
  //         number: false,
  //         list: false,
  //         view: false,
  //         add: false,
  //         edit: false,
  //         sort: true,
  //         filtersearch: false,
  //         relation: false,
  //         relation_table: '',
  //         relation_field: '',
  //         relation_display: '',
  //         parent_filter: [],
  //         required: false,
  //         readonly: false,
  //         default: '',
  //         file: false,
  //       },
  //       {
  //         name: 'created_by',
  //         label: 'Id',
  //         primary: true,
  //         type: 'NO',
  //         validate: 'INTEGER',
  //         number: false,
  //         list: false,
  //         view: false,
  //         add: false,
  //         edit: false,
  //         sort: true,
  //         filtersearch: false,
  //         relation: false,
  //         relation_table: '',
  //         relation_field: '',
  //         relation_display: '',
  //         parent_filter: [],
  //         required: false,
  //         readonly: false,
  //         default: '',
  //         file: false,
  //       },
  //       {
  //         name: 'updated_by',
  //         label: 'Id',
  //         primary: true,
  //         type: 'NO',
  //         validate: 'INTEGER',
  //         number: false,
  //         list: false,
  //         view: false,
  //         add: false,
  //         edit: false,
  //         sort: true,
  //         filtersearch: false,
  //         relation: false,
  //         relation_table: '',
  //         relation_field: '',
  //         relation_display: '',
  //         parent_filter: [],
  //         required: false,
  //         readonly: false,
  //         default: '',
  //         file: false,
  //       },
  //       {
  //         name: 'created_at',
  //         label: 'Id',
  //         primary: true,
  //         type: 'NO',
  //         validate: 'INTEGER',
  //         number: false,
  //         list: false,
  //         view: false,
  //         add: false,
  //         edit: false,
  //         sort: true,
  //         filtersearch: false,
  //         relation: false,
  //         relation_table: '',
  //         relation_field: '',
  //         relation_display: '',
  //         parent_filter: [],
  //         required: false,
  //         readonly: false,
  //         default: '',
  //         file: false,
  //       },
  //       {
  //         name: 'updated_at',
  //         label: 'Id',
  //         primary: true,
  //         type: 'NO',
  //         validate: 'INTEGER',
  //         number: false,
  //         list: false,
  //         view: false,
  //         add: false,
  //         edit: false,
  //         sort: true,
  //         filtersearch: false,
  //         relation: false,
  //         relation_table: '',
  //         relation_field: '',
  //         relation_display: '',
  //         parent_filter: [],
  //         required: false,
  //         readonly: false,
  //         default: '',
  //         file: false,
  //       },
  //     ],
  //   },
  // ];
  tables: any = ['presensi', 'karyawan', 'divisi', 'cuti'];
  models: any = {};
  constructor(public api: Api) {
    let get_model = localStorage.getItem('models');
    if (get_model) {
      this.models = JSON.parse(get_model);
    }
  }

  public async getAllModel() {
    for (let table of this.tables) {
      await this.api
        .model({
          path: `generate/${table}`,
        })
        .then(async (res) => {
          this.models[table] = res;
        })
        .catch((err) => {
          // return reject(err);
        });
    }
    localStorage.setItem('models', JSON.stringify(this.models));
  }

  public async getMeta(model: string, type: string = ''): Promise<any> {
    return new Promise(async (resolve, reject) => {
      let tmp_type = '';
      let tmp_model = this.models[model];
      if (type) {
        tmp_type = 'field' + type;
        tmp_model = this.models[model][tmp_type];
      } else {
        console.log('tidak ada type');
        tmp_model = this.models[model];
      }
      if (tmp_model) {
        return resolve(tmp_model);
      } else {
        return reject({});
      }
    });
  }
}
